export type ImportProduct = {
  name: string;
  slug: string;
  category: string;
  basePrice: number;
  image: string;
  description: string;
  sizes?: string[];
  colors?: string[];
  badge?: string;
};

export const IMPORT_MARGIN = 250;

export const WOMENS_COLLECTION: ImportProduct[] = [
  // ===== WOMEN'S UNSTITCHED =====
  {
    name: "Digital Print Lawn 2-Piece Suit",
    slug: "mw-digital-print-lawn-2pc",
    category: "Women's Unstitched",
    basePrice: 1180,
    image: "https://images.pexels.com/photos/31874449/pexels-photo-31874449.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Premium quality digital print lawn 2-piece unstitched suit. Soft fabric with vibrant colours, perfect for summer wear and casual gatherings.",
    colors: ["Digital Print", "Multicolor"],
    badge: "Best Seller",
  },
  {
    name: "Embroidered Lawn 3-Piece Unstitched",
    slug: "mw-embroidered-lawn-3pc-unstitched",
    category: "Women's Unstitched",
    basePrice: 2100,
    image: "https://images.pexels.com/photos/36567522/pexels-photo-36567522.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Elegant embroidered lawn 3-piece unstitched suit with dupatta. Beautiful threadwork detailing on premium lawn fabric.",
    colors: ["Pink", "Green", "Blue"],
    badge: "New Arrival",
  },
  {
    name: "Cotton Karandi Unstitched Suit",
    slug: "mw-cotton-karandi-unstitched",
    category: "Women's Unstitched",
    basePrice: 1550,
    image: "https://images.pexels.com/photos/36552718/pexels-photo-36552718.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Comfortable cotton karandi unstitched suit, ideal for daily wear. Breathable fabric with elegant print design.",
    colors: ["Yellow", "Beige", "Peach"],
    badge: "Daily Wear",
  },
  {
    name: "Printed Cambric 2-Piece Unstitched",
    slug: "mw-printed-cambric-2pc",
    category: "Women's Unstitched",
    basePrice: 1299,
    image: "https://images.pexels.com/photos/36634895/pexels-photo-36634895.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Stylish printed cambric 2-piece unstitched suit. Light weight fabric with attractive patterns.",
    colors: ["Purple", "Maroon"],
    badge: "Trending",
  },

  // ===== WOMEN'S STITCHED =====
  {
    name: "Embroidered Chiffon Maxi & Trouser Set",
    slug: "mw-embroidered-chiffon-maxi-trouser",
    category: "Women's Stitched",
    basePrice: 3150,
    image: "https://images.pexels.com/photos/20777181/pexels-photo-20777181.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Gorgeous embroidered chiffon maxi with matching trouser. Perfect for formal events, weddings and dinner parties.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Purple", "Maroon", "Green"],
    badge: "Premium",
  },
  {
    name: "Fancy Embroidered 3-Piece Stitched Suit",
    slug: "mw-fancy-embroidered-3pc-stitched",
    category: "Women's Stitched",
    basePrice: 2225,
    image: "https://images.pexels.com/photos/31874448/pexels-photo-31874448.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Beautiful fancy embroidered 3-piece stitched suit for festive occasions and casual gatherings. Ready to wear.",
    sizes: ["S", "M", "L"],
    colors: ["Green", "White", "Pink"],
    badge: "Festive",
  },
  {
    name: "Elegant Belt Robe Dress",
    slug: "mw-elegant-belt-robe-dress",
    category: "Women's Stitched",
    basePrice: 2246,
    image: "https://images.pexels.com/photos/29699410/pexels-photo-29699410.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Elegant robe dress with belt detailing. A soft feminine silhouette for stylish casual and semi-formal looks.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Black", "Maroon"],
    badge: "New Arrival",
  },
  {
    name: "Georgette Bow Top Maxi Set",
    slug: "mw-georgette-bow-top-maxi",
    category: "Women's Stitched",
    basePrice: 1450,
    image: "https://images.pexels.com/photos/31874440/pexels-photo-31874440.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Graceful georgette bow top maxi set — modest and elegant. Perfect for brunches and family events.",
    sizes: ["S", "M", "L"],
    colors: ["Green", "White", "Beige"],
    badge: "Trending",
  },
  {
    name: "Modest Abaya Style Long Dress",
    slug: "mw-modest-abaya-style-dress",
    category: "Women's Stitched",
    basePrice: 2990,
    image: "https://images.pexels.com/photos/18895486/pexels-photo-18895486.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Modest abaya-inspired long dress with elegant silhouette. Comfortable styling for daily wear and formal occasions.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Maroon"],
    badge: "Modest Wear",
  },
  {
    name: "Embroidered Shirt & Skirt Set",
    slug: "mw-embroidered-shirt-skirt-set",
    category: "Women's Stitched",
    basePrice: 1029,
    image: "https://images.pexels.com/photos/38509773/pexels-photo-38509773.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Fancy embroidered shirt and skirt set. Suitable for casual gatherings and themed events.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Pink", "Green"],
    badge: "Hot Pick",
  },

  // ===== 14 AUGUST SPECIAL =====
  {
    name: "14 August Fancy Embroidered Green Suit",
    slug: "mw-14aug-fancy-green-suit",
    category: "14 August Special",
    basePrice: 2225,
    image: "https://images.pexels.com/photos/28837083/pexels-photo-28837083.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Celebrate Pakistan's Independence Day with this fancy green embroidered 3-piece suit. Perfect for Azaadi festivities! 🇵🇰",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "White"],
    badge: "🇵🇰 14 August",
  },
  {
    name: "Azaadi Green & White Dupatta Set",
    slug: "mw-azaadi-green-white-dupatta",
    category: "14 August Special",
    basePrice: 899,
    image: "https://images.pexels.com/photos/36567522/pexels-photo-36567522.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Green and white themed dupatta set for 14 August celebrations. Show your patriotic spirit in style!",
    colors: ["Green", "White"],
    badge: "🇵🇰 Azaadi",
  },
  {
    name: "Pakistan Day Green Embroidered Kurti",
    slug: "mw-pak-day-green-kurti",
    category: "14 August Special",
    basePrice: 1650,
    image: "https://images.pexels.com/photos/31874449/pexels-photo-31874449.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Beautiful green embroidered kurti for Pakistan Day celebrations. Elegant festive wear with patriotic colours.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green"],
    badge: "🇵🇰 Special",
  },

  // ===== COSMETICS =====
  {
    name: "Matte Lipstick Collection (5 Shades)",
    slug: "mw-matte-lipstick-5-shades",
    category: "Cosmetics",
    basePrice: 750,
    image: "https://images.pexels.com/photos/29229006/pexels-photo-29229006.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Premium matte lipstick set with 5 gorgeous shades. Long-lasting, smudge-proof formula. Perfect for every occasion.",
    colors: ["Red", "Nude", "Pink", "Maroon", "Coral"],
    badge: "Best Seller",
  },
  {
    name: "Professional Makeup Brush Set (12 Pcs)",
    slug: "mw-pro-makeup-brush-set-12",
    category: "Cosmetics",
    basePrice: 1200,
    image: "https://images.pexels.com/photos/7588597/pexels-photo-7588597.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "12-piece professional makeup brush set with soft synthetic bristles. Includes all essential brushes for a flawless look.",
    badge: "Professional",
  },
  {
    name: "Lipstick & Lip Liner Duo Set",
    slug: "mw-lipstick-liner-duo",
    category: "Cosmetics",
    basePrice: 550,
    image: "https://images.pexels.com/photos/7256140/pexels-photo-7256140.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Matching lipstick and lip liner duo for precise, long-lasting colour. Perfect pairing for a polished look.",
    colors: ["Red", "Pink", "Nude"],
    badge: "Value Pack",
  },
  {
    name: "Full Face Makeup Kit",
    slug: "mw-full-face-makeup-kit",
    category: "Cosmetics",
    basePrice: 2500,
    image: "https://images.pexels.com/photos/7290640/pexels-photo-7290640.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Complete face makeup kit with foundation, concealer, blush, eyeshadow palette, mascara and setting spray. Everything you need!",
    badge: "Complete Kit",
  },

  // ===== UNDERGARMENTS =====
  {
    name: "Premium Lace Lingerie Set",
    slug: "mw-premium-lace-lingerie-set",
    category: "Undergarments",
    basePrice: 1100,
    image: "https://images.pexels.com/photos/9356540/pexels-photo-9356540.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Elegant premium lace lingerie set with comfortable fit. Soft fabric with beautiful lace detailing.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Maroon", "Black", "White"],
    badge: "Premium",
  },
  {
    name: "Comfortable Cotton Bra & Panty Set (3 Pack)",
    slug: "mw-cotton-bra-panty-3pack",
    category: "Undergarments",
    basePrice: 850,
    image: "https://images.pexels.com/photos/7281290/pexels-photo-7281290.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "3-pack comfortable cotton undergarments set. Breathable fabric for all-day comfort. Available in multiple sizes.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Nude", "Black"],
    badge: "Value Pack",
  },
  {
    name: "Lace Detail Intimate Set",
    slug: "mw-lace-detail-intimate-set",
    category: "Undergarments",
    basePrice: 950,
    image: "https://images.pexels.com/photos/26968036/pexels-photo-26968036.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Delicate lace detail intimate set with premium fabric finish. Designed for comfort and confidence.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Red", "White"],
    badge: "New Arrival",
  },

  // ===== JEWELLERY =====
  {
    name: "Gold Plated Fashion Jewellery Set",
    slug: "mw-gold-plated-jewellery-set",
    category: "Jewellery",
    basePrice: 899,
    image: "https://images.pexels.com/photos/28347073/pexels-photo-28347073.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Stunning gold plated jewellery set with necklace, earrings and tikka. Perfect for weddings and festive occasions.",
    colors: ["Gold"],
    badge: "Wedding",
  },
  {
    name: "Elegant Pearl & Gold Pendant Set",
    slug: "mw-pearl-gold-pendant-set",
    category: "Jewellery",
    basePrice: 750,
    image: "https://images.pexels.com/photos/32780784/pexels-photo-32780784.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Elegant pearl and gold pendant necklace with matching earrings. A timeless accessory for every outfit.",
    colors: ["Gold", "Pearl"],
    badge: "Elegant",
  },
  {
    name: "Traditional Bridal Jewellery Complete Set",
    slug: "mw-traditional-bridal-set",
    category: "Jewellery",
    basePrice: 2200,
    image: "https://images.pexels.com/photos/29038003/pexels-photo-29038003.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Complete traditional bridal jewellery set with matha patti, necklace, earrings and bangles. Stunning for your special day.",
    colors: ["Gold", "Kundan"],
    badge: "Bridal",
  },
  {
    name: "Statement Gold Earrings",
    slug: "mw-statement-gold-earrings",
    category: "Jewellery",
    basePrice: 450,
    image: "https://images.pexels.com/photos/7615245/pexels-photo-7615245.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Beautiful statement gold earrings for daily wear and special occasions. Lightweight and comfortable.",
    colors: ["Gold", "Silver"],
    badge: "Affordable",
  },

  // ===== HANDBAGS =====
  {
    name: "Premium Fashion Shoulder Bag",
    slug: "mw-premium-shoulder-bag",
    category: "Handbags",
    basePrice: 1850,
    image: "https://images.pexels.com/photos/18601568/pexels-photo-18601568.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Stylish premium shoulder bag for everyday use. Pairs beautifully with eastern and western outfits.",
    colors: ["Black", "Brown", "Beige"],
    badge: "Best Seller",
  },
  {
    name: "Elegant Crossbody Handbag",
    slug: "mw-elegant-crossbody-bag",
    category: "Handbags",
    basePrice: 1650,
    image: "https://images.pexels.com/photos/20086702/pexels-photo-20086702.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Chic crossbody handbag with modern design. Perfect for outings, university, office and casual events.",
    colors: ["Red", "Black", "Camel"],
    badge: "Hot Pick",
  },
  {
    name: "Women's Casual Tote Bag",
    slug: "mw-womens-casual-tote",
    category: "Handbags",
    basePrice: 1950,
    image: "https://images.pexels.com/photos/29793778/pexels-photo-29793778.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Roomy casual tote bag for daily use, shopping and office essentials. Quality leather finish.",
    colors: ["Tan", "Black", "Beige"],
    badge: "Daily Essential",
  },

  // ===== SHOES =====
  {
    name: "Classic Black Fashion Heels",
    slug: "mw-classic-black-heels",
    category: "Shoes",
    basePrice: 2100,
    image: "https://images.pexels.com/photos/10686370/pexels-photo-10686370.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Classic black heels for parties, formal events and everyday elegant styling. Comfortable fit with timeless design.",
    sizes: ["36", "37", "38", "39", "40", "41"],
    colors: ["Black"],
    badge: "Classic",
  },
  {
    name: "Strappy Sandal Heel",
    slug: "mw-strappy-sandal-heel",
    category: "Shoes",
    basePrice: 1850,
    image: "https://images.pexels.com/photos/6920411/pexels-photo-6920411.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Fashionable strappy sandal heel for weddings, dinners and special outings. Stunning red finish.",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Red", "Gold", "Black"],
    badge: "Party Wear",
  },
  {
    name: "Pointed Toe Kitten Heel Mules",
    slug: "mw-pointed-toe-mules",
    category: "Shoes",
    basePrice: 1500,
    image: "https://images.pexels.com/photos/33659069/pexels-photo-33659069.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Chic pointed-toe kitten heel mules blending comfort with style. Perfect for office and evening wear.",
    sizes: ["36", "37", "38", "39", "40", "41"],
    colors: ["Black", "Nude"],
    badge: "Versatile",
  },

  // ===== ACCESSORIES =====
  {
    name: "Bride Sash Gold Foil Satin",
    slug: "mw-bride-sash-gold-foil",
    category: "Accessories",
    basePrice: 252,
    image: "https://images.pexels.com/photos/8990700/pexels-photo-8990700.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    description: "Elegant white bride sash with gold foil finish. Perfect for bridal shower, dholki, mehndi and themed events.",
    colors: ["White", "Gold"],
    badge: "Event Wear",
  },
];
